### ISSUE TITLE
Decommission this repository and app

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-redirects#6]
[pages-redirects](https://github.com/18f/pages-redirects) now supersedes all functionality of this app, so this one should be decommissioned.

To Do:
- [x] Mark repo as archived via a tag
- [x] Update README accordingly (#5)
- [x] Delete `federalist-redirect` app in cloud.gov (`gsa-18f-federalist` | `redirects`)
- [x] Delete associated deployer service (`federalist-redirects-deployer`)

**Comment by jseppi** [comment]
@wslack sound good to you?

**Comment by wslack** [comment]
@jseppi this looks good

**Comment by jseppi** [comment]
@wslack: Great. All tasks except the repo tag are done. I don't have admin access to this repo, so if you do, could you add the appropriate tag and close this out?

**Comment by jmhooper** [comment]
@jseppi: Adding the tag now
